# Generated by Django 4.1.4 on 2022-12-20 21:58

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStreaming', '0002_alter_evento_finstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='inicioStream',
            field=models.DateTimeField(verbose_name=builtins.input),
        ),
    ]
