# Generated by Django 4.1.4 on 2022-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStreaming', '0004_alter_evento_iniciostream'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(to='appStreaming.categoriaevento'),
        ),
    ]
