# Generated by Django 4.1.4 on 2022-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStreaming', '0005_evento_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='finStream',
            field=models.DateTimeField(),
        ),
    ]
