# Generated by Django 4.1.4 on 2022-12-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStreaming', '0006_alter_evento_finstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fechaConfirmacion',
        ),
    ]
