# Generated by Django 4.1.4 on 2022-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStreaming', '0007_remove_evento_fechaconfirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fechaConfirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
